
resume_parsing_task:
  description: >
    Parse and summarize a candidate's resume (PDF or DOCX).

    Extract key personal and professional information relevant for evaluating the candidate.
    Focus on:
    - Identifying name
    - Writing a professional summary that includes total years of experience, education, and certifications
    - Listing relevant skills

    CANDIDATE RESUME
    ----------------
    {resume_text}

    ADDITIONAL INSTRUCTIONS
    -----------------------
    Your output MUST be a valid JSON with these fields:
    - "name": Candidate's full name (used as unique identifier)
    - "email": The candidate’s email address (if available)
    - "bio": A concise paragraph including total years of experience, education, and certifications
    - "skills": List of key skills from resume or inferred (comma-separated string)

  expected_output: >
    A structured JSON object with the following keys only:name, email, bio, skills.
    Do NOT include explanations, markdown, or additional commentary.
  agent: resume_parser_agent

resume_keyword_extraction_task:
  description: >
    Based on the structured resume data, extract a list of relevant keywords.

    Focus areas:
    - Job titles, skills, technologies, certifications, and industry terminology
    - Avoid duplicates or irrelevant/filler words

    Input: A JSON object with fields: name, email, bio, skills.
    
    ADDITIONAL INSTRUCTIONS
    -----------------------
    Your output MUST be a valid JSON with these fields:
    - "name": Candidate's full name (used as unique identifier)
    - "email": The candidate’s email address (if available)
    - "bio": A concise paragraph including total years of experience, education, and certifications
    - "skills": List of key skills from resume or inferred (comma-separated string)
    - "keywords": List of relevant keywords (comma-separated string)
    
  expected_output: >
    A structured JSON object with the following keys only:name, email, bio, skills, keywords.
    Do NOT include explanations, markdown, or additional commentary.
  agent: resume_keyword_agent


  

  